services:
  - type: web
    name: metadata-classification-api
    runtime: docker
    plan: starter
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: OPENAI_DEFAULT_MODEL
        value: gpt-4o-mini
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 10000
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FORMAT
        value: json
      - key: CACHE_TTL_SECONDS
        value: 3600
      - key: CACHE_MAX_SIZE
        value: 1000
      - key: RATE_LIMIT_REQUESTS_PER_MINUTE
        value: 60
      - key: HTTP_TIMEOUT_SECONDS
        value: 30
      - key: OPENAI_TIMEOUT_SECONDS
        value: 60
    healthCheckPath: /health
    buildCommand: ""
    startCommand: "uvicorn src.main:app --host 0.0.0.0 --port 10000"
